#!/bin/bash

set -e

POLARIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HYPR_CONFIG="$HOME/.config/hypr"
NPROC=$(nproc)

echo "╔══════════════════════════════════════╗"
echo "║   Polaris Desktop Environment        ║"
echo "║   Install Script                     ║"
echo "╚══════════════════════════════════════╝"
echo ""

# ─── 1. Dependencies ───────────────────────
echo "▶ Installing dependencies..."
paru -S --needed --noconfirm \
    cmake \
    qt6-base qt6-declarative qt6-wayland \
    layer-shell-qt qt6-5compat \
    mako kitty fastfetch \
    brightnessctl fd \
    hyprpaper

echo "✓ Dependencies installed"
echo ""

# ─── 2. Build ──────────────────────────────
echo "▶ Building Polaris..."
cmake -B "$POLARIS_DIR/cmake-build-release" \
      -DCMAKE_BUILD_TYPE=Release \
      -S "$POLARIS_DIR"

cmake --build "$POLARIS_DIR/cmake-build-release" \
      --target all \
      -j "$NPROC"

echo "✓ Build complete"
echo ""

# ─── 3. Install binaries ───────────────────
echo "▶ Installing binaries to /usr/local/bin..."
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/launcher/polaris_launcher"   /usr/local/bin/polaris_launcher
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/taskbar/polaris_taskbar"     /usr/local/bin/polaris_taskbar
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/settings/polaris_settings"   /usr/local/bin/polaris_settings
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/osd/polaris_osd"             /usr/local/bin/polaris_osd
sudo install -Dm755 "$POLARIS_DIR/cmake-build-release/modules/wallpaper/polaris_wallpaper" /usr/local/bin/polaris_wallpaper

echo "✓ Binaries installed"
echo ""

# ─── 4. Dotfiles symlink ───────────────────
echo "▶ Linking dotfiles..."

# Kitty
mkdir -p "$HOME/.config/kitty"
if [ ! -e "$HOME/.config/kitty/kitty.conf" ]; then
    ln -s "$POLARIS_DIR/dotfiles/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
    echo "  ✓ kitty.conf linked"
else
    echo "  ⚠ kitty.conf already exists, skipping"
fi

# Fastfetch
mkdir -p "$HOME/.config/fastfetch"
if [ ! -e "$HOME/.config/fastfetch/config.jsonc" ]; then
    ln -s "$POLARIS_DIR/dotfiles/fastfetch/config.jsonc" "$HOME/.config/fastfetch/config.jsonc"
    echo "  ✓ fastfetch config linked"
else
    echo "  ⚠ fastfetch config already exists, skipping"
fi

# Mako
mkdir -p "$HOME/.config/mako"
if [ ! -e "$HOME/.config/mako/config" ]; then
    ln -s "$POLARIS_DIR/dotfiles/mako/config" "$HOME/.config/mako/config"
    echo "  ✓ mako config linked"
else
    echo "  ⚠ mako config already exists, skipping"
fi

echo "✓ Dotfiles linked"
echo ""

# ─── 5. Hyprland config ───
echo "▶ Setting up Hyprland config..."

mkdir -p "$HYPR_CONFIG/modules"

# Backup hyprland.lua
if [ -f "$HYPR_CONFIG/hyprland.lua" ]; then
    cp "$HYPR_CONFIG/hyprland.lua" "$HYPR_CONFIG/hyprland.lua.backup"
    echo "  ✓ Backed up hyprland.lua → hyprland.lua.backup"
fi


cat > "$HYPR_CONFIG/modules/polaris.lua" << 'EOF'
-- Polaris Desktop Environment Module
-- Auto-generated by install.sh

-- 1. Autostart (Event-driven syntax)
hl.on("hyprland.start", function ()
    hl.exec_cmd("polaris_taskbar")
end)

-- 2. Window rules
hl.window_rule({
    match = { class = "polaris_launcher" },
    float = true,
    move = "390 320",
    decorate = false,
    opacity = 0.8,
})

hl.window_rule({
    match = { class = "polaris_settings" },
    float = true,
    move = "center center",
    decorate = false,
})

-- 3. Keybinds (Dispatcher syntax)
local mainMod = "SUPER"
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("polaris_launcher"))
hl.bind("ALT + S", hl.dsp.exec_cmd("polaris_settings"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("polaris_wallpaper"))

-- 4. OSD Keybinds
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ ; polaris_osd --volume up"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- ; polaris_osd --volume down"), { locked = true, repeating = true })

hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+ ; polaris_osd --brightness up"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%- ; polaris_osd --brightness down"), { locked = true, repeating = true })
EOF

echo "  ✓ Created $HYPR_CONFIG/modules/polaris.lua with correct syntax"

if [ -f "$HYPR_CONFIG/hyprland.lua" ]; then
    if ! grep -q "polaris" "$HYPR_CONFIG/hyprland.lua"; then
        echo "" >> "$HYPR_CONFIG/hyprland.lua"
        echo "-- Polaris DE Module Loading" >> "$HYPR_CONFIG/hyprland.lua"


        if ! grep -q "function safety_require" "$HYPR_CONFIG/hyprland.lua"; then
            cat >> "$HYPR_CONFIG/hyprland.lua" << 'EOF'
function safety_require(module_path)
    local success, result = pcall(require, module_path)
    if not success then
        print("-> Can not find path: " .. module_path)
        print("-> Error: " .. tostring(result))
    else
        return result
    end
end
EOF
            echo "  ✓ Injected safety_require function into hyprland.lua"
        fi

        echo "safety_require(\"modules/polaris\")" >> "$HYPR_CONFIG/hyprland.lua"
        echo "  ✓ Added polaris module to hyprland.lua"
    else
        echo "  ⚠ polaris already required in hyprland.lua, skipping"
    fi
fi

echo "✓ Hyprland config done"

# ─── Done ──────────────────────────────────
echo "╔══════════════════════════════════════╗"
echo "║   Installation complete!             ║"
echo "║                                      ║"
echo "║   Reload Hyprland to apply:          ║"
echo "║   Ctrl + Super + Alt + R             ║"
echo "╚══════════════════════════════════════╝"